/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package solverde;

import java.io.*;


/**
 *
 * @author jamie
 */
public class RecoveryGUI extends javax.swing.JFrame {

    /**
     * Creates new form recoveryGUI
     */
    public RecoveryGUI() {
        initComponents();
    }
    
    //search method to search the txt file for the correct account
    
    private String findAccount(String email, String phone, String secQ){
        try(BufferedReader br = new BufferedReader(new FileReader("users.txt"))){
            String line;
            while((line = br.readLine()) != null){
                String[] parts = line.split(",");
                
                if (parts.length>= 6){
                    String fileEmail = parts[3].trim();
                    String filePhone = parts[4].trim();
                    String fileSecQ = parts[5].trim();
                    if (email.equals(fileEmail) && phone.equals(filePhone) && secQ.equals(fileSecQ)) {
                        return parts[0];
                    }
                }
            }
        } catch (IOException e){
            javax.swing.JOptionPane.showMessageDialog(this, "error finding file" + e.getMessage());
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EmailRecovery = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PhoneNumberRecovery = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SecurityQuestionRecovery = new javax.swing.JTextField();
        ResetPassword = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SolVerde Account Recovery");

        jButton1.setText("Login ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("return to login page");

        jLabel3.setText("Please enter the Email and Phone number you used to create your account");

        jLabel4.setText("Email");

        EmailRecovery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailRecoveryActionPerformed(evt);
            }
        });

        jLabel6.setText("Phone Number");

        PhoneNumberRecovery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberRecoveryActionPerformed(evt);
            }
        });

        jLabel7.setText("Answer the Secuirty Question below ");

        jLabel8.setText("what is your Mothers Maiden name?");

        SecurityQuestionRecovery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecurityQuestionRecoveryActionPerformed(evt);
            }
        });

        ResetPassword.setText("Reset Password");
        ResetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jButton1))
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ResetPassword)
                                .addComponent(SecurityQuestionRecovery, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(EmailRecovery)
                                .addComponent(PhoneNumberRecovery, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(EmailRecovery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(PhoneNumberRecovery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(SecurityQuestionRecovery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ResetPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoginGUI LoginGUI = new LoginGUI();
        LoginGUI.setVisible(true);
        //closes the current page//
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EmailRecoveryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EmailRecoveryActionPerformed
    {//GEN-HEADEREND:event_EmailRecoveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailRecoveryActionPerformed

    private void PhoneNumberRecoveryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PhoneNumberRecoveryActionPerformed
    {//GEN-HEADEREND:event_PhoneNumberRecoveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberRecoveryActionPerformed

    private void ResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetPasswordActionPerformed
        //take user details from email, phone number and security question//
        
        String email = EmailRecovery.getText().trim();
        String phone = PhoneNumberRecovery.getText().trim();
        String secQ = SecurityQuestionRecovery.getText().trim();
        
        //check user input field are filled//
        
        if (email.isEmpty()||phone.isEmpty()||secQ.isEmpty())
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Please Fill in all Fields");
                return;
            }
        
        //check if Email is in correct Format
        if (!email.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"))
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter correct Email Format");
            return;
        }
        
        //check if Phone Number is in correct Format
        
        if(!phone.matches("^\\+?[0-9]{7,15}$"))
        {
            javax.swing.JOptionPane.showMessageDialog(this,"Please enter correct Phone Format");
            return;
        }
        
        //after validation, search for the correct account in the .txt file, and grabs the usernameof that account, then opens the password reset Page
        String username = findAccount(email,phone,secQ);
        
        if (username != null) {
            //opens the ResetPasswordGUI under the found account
            ResetPasswordGUI resetPasswordGUI = new ResetPasswordGUI(username);
            resetPasswordGUI.setVisible(true);
            //closes the current page//
            this.dispose();
            //if there is no accounts in the txt file under this info://
        } else{
            javax.swing.JOptionPane.showMessageDialog(this,"No account found with that information, please create account");
            return;
                    
        }  
    }//GEN-LAST:event_ResetPasswordActionPerformed

    private void SecurityQuestionRecoveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecurityQuestionRecoveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecurityQuestionRecoveryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecoveryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecoveryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecoveryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecoveryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoveryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailRecovery;
    private javax.swing.JTextField PhoneNumberRecovery;
    private javax.swing.JButton ResetPassword;
    private javax.swing.JTextField SecurityQuestionRecovery;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
