/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author jamie
 */

package solverde;
//import javax.crypto.Cipher;
//import javax.crypto.KeyGenerator;
//import javax.crypto.SecretKey;
//imports for hashing, salting, base64 and fileWriting
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.util.Base64;
import java.io.File;
import java.io.FileWriter;



public class RegisterGUI extends javax.swing.JFrame {

    /**
     * Creates new form registerGUI
     */
    public RegisterGUI() 
    {
        initComponents();
        try 
            {
   //        generateKey();
            }
        catch (Exception e)
        {
        }
    }
    
  //  private SecretKey secretKey;
    //secureRandom generates secure radnom bytes
    private final SecureRandom rng = new SecureRandom();
    
    
    
    //random salt for hashing password
    private byte[] makeSalt()
    {
        byte[] salt = new byte[8];  //byte array length 8bytes
        rng.nextBytes(salt);        // random bytes 
        return salt;                // returns the randomised salt
    }
    
    //called once for AES keyt
  //  private void generateKey() throws Exception 
  //  {
  //      KeyGenerator keyGen = KeyGenerator.getInstance("AES");
   //     keyGen.init(128);   //128 bit AESkey
   //     secretKey = keyGen.generateKey();
   //  }
    
    //take password + salt > hashes using hashSha256 > returns as base64
     private String hashSha256(String password, byte[] salt) throws Exception
     {
        MessageDigest messageDigest = MessageDigest.getInstance("SHA-256");
        messageDigest.update(salt);
        byte[] hash = messageDigest.digest(password.getBytes());
        return Base64.getEncoder().encodeToString(hash);        //convert hash into base64 to save
     }
    
    
// returns base64 text to store in a file.
//private String encryptAES(String plaintext) throws Exception 
 //   {
 //       Cipher cipher = Cipher.getInstance("AES");            
  //      cipher.init(Cipher.ENCRYPT_MODE, secretKey);
 //       byte[] out = cipher.doFinal(plaintext.getBytes());
  //      return Base64.getEncoder().encodeToString(out);
  //  }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoginPageButton = new javax.swing.JButton();
        UsernameInput = new javax.swing.JTextField();
        EmailInput = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PhoneNumberInput = new javax.swing.JTextField();
        PhoneNumberLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SecurityQLabel = new javax.swing.JLabel();
        SecurityQInput = new javax.swing.JTextField();
        CreateAccountButton = new javax.swing.JButton();
        PasswordInput = new javax.swing.JPasswordField();
        ConfirmPasswordInput = new javax.swing.JPasswordField();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registration Page");

        jLabel2.setText("click here to return to login page");

        LoginPageButton.setText("Login Page");
        LoginPageButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                LoginPageButtonActionPerformed(evt);
            }
        });

        UsernameInput.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                UsernameInputActionPerformed(evt);
            }
        });

        EmailInput.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EmailInputActionPerformed(evt);
            }
        });

        UsernameLabel.setText("Username");

        PasswordLabel.setText("Password");

        ConfirmPasswordLabel.setText("Confirm Password");

        EmailLabel.setText("Email");

        jLabel7.setText("Create an account by entering the following information");

        PhoneNumberInput.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PhoneNumberInputActionPerformed(evt);
            }
        });

        PhoneNumberLabel.setText("Phone Number");

        jLabel10.setText("Answer the Security Question for recovery purposes");

        SecurityQLabel.setText("What is your mother maidens name?");

        SecurityQInput.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SecurityQInputActionPerformed(evt);
            }
        });

        CreateAccountButton.setText("Create Account");
        CreateAccountButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CreateAccountButtonActionPerformed(evt);
            }
        });

        PasswordInput.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PasswordInputActionPerformed(evt);
            }
        });

        ConfirmPasswordInput.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ConfirmPasswordInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PhoneNumberLabel)
                                .addGap(22, 22, 22)
                                .addComponent(PhoneNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ConfirmPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EmailInput, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(UsernameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(ConfirmPasswordInput)
                                    .addComponent(PasswordInput)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SecurityQLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SecurityQInput, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CreateAccountButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel7)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LoginPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(PasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPasswordLabel)
                    .addComponent(ConfirmPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberLabel)
                    .addComponent(PhoneNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SecurityQLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SecurityQInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreateAccountButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginPageButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginPageButtonActionPerformed
        LoginGUI LoginGUI = new LoginGUI();
        LoginGUI.setVisible(true);
        //closes the current page
        this.dispose();
    }//GEN-LAST:event_LoginPageButtonActionPerformed

    private void PhoneNumberInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberInputActionPerformed

    private void UsernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameInputActionPerformed

    private void EmailInputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EmailInputActionPerformed
    {//GEN-HEADEREND:event_EmailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailInputActionPerformed

    private void SecurityQInputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SecurityQInputActionPerformed
    {//GEN-HEADEREND:event_SecurityQInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecurityQInputActionPerformed

    private void CreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CreateAccountButtonActionPerformed
    {//GEN-HEADEREND:event_CreateAccountButtonActionPerformed
    // TODO add your handling code here: // CREATE ACCOUNT BUTTON SHOULD HASH + ENCRYPT AND SAVE TO TXT FILE
        
    //takes value sfrom text input
    String username = UsernameInput.getText().trim();
    String password = new String(PasswordInput.getPassword());
    String confirm = new String(ConfirmPasswordInput.getPassword());
    String email = EmailInput.getText().trim();
    String phone = PhoneNumberInput.getText().trim();
    String secQ = SecurityQInput.getText().trim();
    
    //check inputs are empty and if true then return error message "pls fill in all fielsd"
    if (username.isEmpty() || password.isEmpty() || confirm.isEmpty() || email.isEmpty() || phone.isEmpty() || secQ.isEmpty())
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields");
            return;
        }
   
    //check if passwords on input match
    if (!password.equals(confirm))
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Passwords do not match");
            return;
        }
    
    //check if email is valid format, (x@mail.com) 
    if (!email.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")) //regex
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid email address");
            return;
        }
    
    //phone number must be numbers (0-9) and between 7-15 chars to allow for different countries phone number systems.
    if (!phone.matches("^\\+?[0-9]{7,15}$")) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid phone number");
            return;
        }
    
    //hash + save. 
    try
        {
        //make salt and hash the password (FOR LOGIN)
            byte[] salt = makeSalt();
            String saltBase64 = Base64.getEncoder().encodeToString(salt);   //convert salt to base64
            String hashBase64 = hashSha256(password, salt);                 
            
        //encrpyt password
        //String encryptedPasswordBase64 = encryptAES(password);
        
        
        //file created where app runs
        File file = new File("users.txt");
        
        String line = String.join(",",username,saltBase64,hashBase64,email,phone,secQ);

        
        
        try(FileWriter fileWriter = new FileWriter(file, true))
            {
            fileWriter.write(line);
            fileWriter.write(System.lineSeparator());   //new line after each entry
            }
        }
    catch (Exception ex) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Problem creating account.");
        }
    //display "account creation" message if all details are filled in 
    javax.swing.JOptionPane.showMessageDialog(this, "Your account has been created. Thank you for joining us!");
    
    //clear fields on validating registration details 
    UsernameInput.setText("");
    PasswordInput.setText("");
    ConfirmPasswordInput.setText("");
    EmailInput.setText("");
    PhoneNumberInput.setText("");
    SecurityQInput.setText("");
    
     

        
        
    }//GEN-LAST:event_CreateAccountButtonActionPerformed

    private void PasswordInputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PasswordInputActionPerformed
    {//GEN-HEADEREND:event_PasswordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordInputActionPerformed

    private void ConfirmPasswordInputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ConfirmPasswordInputActionPerformed
    {//GEN-HEADEREND:event_ConfirmPasswordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPasswordInput;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JButton CreateAccountButton;
    private javax.swing.JTextField EmailInput;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JButton LoginPageButton;
    private javax.swing.JPasswordField PasswordInput;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField PhoneNumberInput;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JTextField SecurityQInput;
    private javax.swing.JLabel SecurityQLabel;
    private javax.swing.JTextField UsernameInput;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
